USE IsBuroKadrov

CREATE TABLE Speciality
(
	ID INT NOT NULL IDENTITY,
	Speciality_Name VARCHAR(30) NOT NULL

	CONSTRAINT PK_Speciality_ID PRIMARY KEY (ID)
)

CREATE TABLE Director
(
	ID INT NOT NULL IDENTITY,
	First_Name VARCHAR(30) NOT NULL,
	Last_Name VARCHAR(30) NOT NULL,
	Birthday DATE NOT NULL,

	CONSTRAINT PK_Director_ID PRIMARY KEY (ID)
)

CREATE TABLE State
(
	ID INT NOT NULL IDENTITY,
	State_Name VARCHAR(50)

	CONSTRAINT PK_Workers_State_ID PRIMARY KEY (ID)
)

CREATE TABLE Profession
(
	ID INT NOT NULL IDENTITY,
	Profession_Name VARCHAR(50) NOT NULL,
	Salary SMALLMONEY NOT NULL

	CONSTRAINT PK_Profession_ID PRIMARY KEY (ID)
)

CREATE TABLE Contract 
(
	ID INT NOT NULL IDENTITY,
	Contract_Number INT NOT NULL,
	Start_Date DATE NOT NULL,
	End_Date DATE NOT NULL,

	CONSTRAINT PK_Contract_ID PRIMARY KEY (ID)
)

----------------------------------------------

CREATE TABLE Company
(
	ID INT NOT NULL IDENTITY,
	Company_Name VARCHAR(30) NOT NULL,
	Base_Date DATE NOT NULL,
	Director_ID INT UNIQUE,

	CONSTRAINT PK_Company_ID PRIMARY KEY (ID),
	FOREIGN KEY (Director_ID) REFERENCES Directors(ID)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,
)

CREATE TABLE Department
(
	ID INT NOT NULL IDENTITY,
	Department_Name VARCHAR(50) NOT NULL,
	Company_ID INT,

	CONSTRAINT PK_Departmant_ID PRIMARY KEY (ID),
	FOREIGN KEY (Company_ID) REFERENCES Company(ID)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,
)

CREATE TABLE Worker
(
	ID INT NOT NULL IDENTITY,
	First_Name VARCHAR(50) NOT NULL,
	Last_Name VARCHAR(50) NOT NULL,
	Phone_Number VARCHAR(50),
	Birthday DATE NOT NULL,

	Speciality_ID INT,
	Department_ID INT

	CONSTRAINT PK_Worker_ID PRIMARY KEY (ID),
	FOREIGN KEY (Speciality_ID) REFERENCES  Speciality(ID)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,
	FOREIGN KEY (Department_ID) REFERENCES Department(ID)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION	
)

CREATE TABLE Employee
(
	ID INT NOT NULL IDENTITY,
	First_Name VARCHAR(30) NOT NULL,
	Last_Name VARCHAR(30) NOT NULL,
	Birthday DATE NOT NULL,

	CONSTRAINT PK_Employee_ID PRIMARY KEY (ID),
)

CREATE TABLE Job_Vacancy
(
	ID INT NOT NULL IDENTITY,
	Receipt_Date DATE NOT NULL,

	Company_ID INT,
	Proffesion_ID INT

	CONSTRAINT PK_JobVacancy_ID PRIMARY KEY (ID)
	FOREIGN KEY (Proffesion_ID ) REFERENCES Proffesion(ID)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,
	FOREIGN KEY (Company_ID) REFERENCES Company(ID)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION,
)

CREATE TABLE Workers_History
(
	Worker_ID INT NOT NULL,
	Company_ID INT,
	Action VARCHAR(30),
	Action_Date DATE NOT NULL

	FOREIGN KEY (Worker_ID) REFERENCES Workers(ID)
	ON UPDATE NO ACTION
	ON DELETE CASCADE,
	FOREIGN KEY (Company_ID) REFERENCES Company(ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,
)
------------------------------------------------------------

CREATE TABLE Workers_Department
(
	Department_ID INT NOT NULL,
	Worker_ID INT NOT NULL,

	FOREIGN KEY (Department_ID) REFERENCES Department(ID)
		ON UPDATE NO ACTION
		ON DELETE CASCADE,
	FOREIGN KEY (Worker_ID) REFERENCES Workers(ID)
		ON UPDATE NO ACTION
		ON DELETE CASCADE,
)
